spring.application.name=School_management
spring.datasource.url = jdbc:mysql://localhost:3306/School
spring.datasource.username = root
spring.datasource.password = 4768


spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

server.port=8080

logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE

# JWT Configuration
auth.token.jwtsecret=your-256-bit-secret-key-here-must-be-at-least-32-characters
auth.token.expirationinmils=86400000