spring.application.name=School_management
spring.datasource.url = jdbc:mysql://localhost:3306/School
spring.datasource.username = root
spring.datasource.password = 4768


spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

server.port=8080

logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE

# JWT Configuration
jwt.secret=2vQ8kR7pLmN4xT9wYcB6hJ3sF1dA5gE8zU0iOqWrPvXnM7tKbCyD4fHsGlQjZaReBuIpVoXmSnYhTkLwQ==
jwt.expiration=86400000